# Generated by Django 3.2.9 on 2021-12-04 07:23

from django.db import migrations, models
import django.db.models.deletion


def add_to_newmodel(apps, schema_editor):
    '''
    Добавление данных в новую модель
    '''
    new_model = apps.get_model("store", "Publisher")
    new_model.objects.create(
        field_1='Field_1 content',
        field_2='Field_2 content'
    )

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.publisher')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.publisher')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.journal')),
            ],
        ),
        # Добавляем данные после создания модели NewModel
        # migrations.RunPython(add_to_newmodel,
        #                      reverse_code=migrations.RunPython.noop)
    ]
