# Generated by Django 3.2.9 on 2021-12-06 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_auto_20211204_1111"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={"verbose_name": "статья", "verbose_name_plural": "статьи"},
        ),
        migrations.AlterModelOptions(
            name="book",
            options={"verbose_name": "книга", "verbose_name_plural": "книги"},
        ),
        migrations.AlterModelOptions(
            name="journal",
            options={"verbose_name": "журнал", "verbose_name_plural": "журналы"},
        ),
        migrations.AlterModelOptions(
            name="publisher",
            options={
                "verbose_name": "издательство",
                "verbose_name_plural": "издательства",
            },
        ),
    ]
