# Generated by Django 3.2.9 on 2021-12-17 18:55

from django.db import migrations, models

from helpers.write_articles import write_data_to_model


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_auto_20211206_1804"),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=200, verbose_name="Имя пользователя"),
                ),
                ("last_name", models.CharField(max_length=200, verbose_name="Фамилия")),
            ],
            options={
                "verbose_name": "автор",
                "verbose_name_plural": "авторы",
            },
        ),
        migrations.AddField(
            model_name="article",
            name="authors",
            field=models.ManyToManyField(to="store.Author"),
        ),
        migrations.AddField(
            model_name="book",
            name="authors",
            field=models.ManyToManyField(to="store.Author"),
        ),
        migrations.RunPython(
            write_data_to_model, reverse_code=migrations.RunPython.noop
        ),
    ]
