# Generated by Django 3.2.9 on 2021-12-18 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_auto_20211217_1855"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="authors",
            field=models.ManyToManyField(null=True, to="store.Author"),
        ),
        migrations.AlterField(
            model_name="book",
            name="authors",
            field=models.ManyToManyField(null=True, to="store.Author"),
        ),
    ]
